name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t my-ci-cd-project .

    - name: Tag Docker image
      run: docker tag my-ci-cd-project ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-project:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-project:latest

    - name: Run Docker container
      run: docker run -d -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-project:latest
