name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Secrets
      run: |
        echo "DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}"
        echo "DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t my-ci-cd-project .

    - name: Tag Docker image
      run: docker tag my-ci-cd-project ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-project:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-project:latest
